### ISSUE TITLE
Driver getting into Panic

### ISSUE THREAD

**Issue by gauravAggrahari** [kubernetes-sigs/azurefile-csi-driver#1037]
Hi, 
When I am trying to do a Dynamic volume provisioning, the driver is getting into a panic state and the controller pods start restarting. 
Below is the log I see in the `csi-provisioner` container.
```
0602 15:24:10.190921       1 azure_storageaccount.go:273] set AllowBlobPublicAccess(false) for storage account(ffd775d64bfc2443e82a32f)
I0602 15:24:30.894703       1 azure_storageaccount.go:330] Creating private endpoint(ffd775d64bfc2443e82a32f-pvtendpoint) for account (ffd775d64bfc2443e82a32f)
E0602 15:24:30.942686       1 runtime.go:79] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 77 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x19afc60, 0x2d526c0})
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:75 +0x85
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:49 +0x75
panic({0x19afc60, 0x2d526c0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).createPrivateEndpoint(0xc000280a80, {0x1eb6db8, 0xc0000ea630}, {0xc0008d5d40, 0x17}, 0xc000868ec0, {0xc0008d4480, 0x23}, {0xc000045a10, 0x17}, ...)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go:337 +0x313
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).EnsureStorageAccount(0xc000280a80, {0x1eb6db8, 0xc0000ea630}, 0xc0002c20e0, {0x1c2a730, 0x1})
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go:308 +0x1abc
sigs.k8s.io/azurefile-csi-driver/pkg/azurefile.(*Driver).CreateVolume.func1()
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/pkg/azurefile/controllerserver.go:371 +0x76
k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0x40cc94, 0xc0005271f8})
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:220 +0x1b
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x1eb6d48, 0xc000040038}, 0x17a3ee5)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:233 +0x7c
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0x1b1fd40)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:226 +0x39
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff({0x0, 0x0, 0x0, 0x1, 0x0}, 0x4)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:421 +0x5f
sigs.k8s.io/azurefile-csi-driver/pkg/azurefile.(*Driver).CreateVolume(0xc000182780, {0x1eb6db8, 0xc0000ea630}, 0xc00009b030)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/pkg/azurefile/controllerserver.go:369 +0x3fda
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler.func1({0x1eb6db8, 0xc0000ea630}, {0x1b4d760, 0xc00009b030})
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5676 +0x78
sigs.k8s.io/azurefile-csi-driver/pkg/csi-common.logGRPC({0x1eb6db8, 0xc0000ea630}, {0x1b4d760, 0xc00009b030}, 0xc0003418a0, 0xc0003a68a0)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/pkg/csi-common/utils.go:79 +0x3ab
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler({0x1bf3400, 0xc000182780}, {0x1eb6db8, 0xc0000ea630}, 0xc0002e8480, 0x1d0eff8)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5678 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a1c00, {0x1ee5428, 0xc00051e780}, 0xc00024fe60, 0xc00049b680, 0x2d60900, 0x0)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/google.golang.org/grpc/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002a1c00, {0x1ee5428, 0xc00051e780}, 0xc00024fe60, 0x0)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/google.golang.org/grpc/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/google.golang.org/grpc/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/google.golang.org/grpc/server.go:919 +0x294
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x1593373]

goroutine 77 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x0})
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:56 +0xd8
panic({0x19afc60, 0x2d526c0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).createPrivateEndpoint(0xc000280a80, {0x1eb6db8, 0xc0000ea630}, {0xc0008d5d40, 0x17}, 0xc000868ec0, {0xc0008d4480, 0x23}, {0xc000045a10, 0x17}, ...)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go:337 +0x313
sigs.k8s.io/cloud-provider-azure/pkg/provider.(*Cloud).EnsureStorageAccount(0xc000280a80, {0x1eb6db8, 0xc0000ea630}, 0xc0002c20e0, {0x1c2a730, 0x1})
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go:308 +0x1abc
sigs.k8s.io/azurefile-csi-driver/pkg/azurefile.(*Driver).CreateVolume.func1()
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/pkg/azurefile/controllerserver.go:371 +0x76
k8s.io/apimachinery/pkg/util/wait.ConditionFunc.WithContext.func1({0x40cc94, 0xc0005271f8})
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:220 +0x1b
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtectionWithContext({0x1eb6d48, 0xc000040038}, 0x17a3ee5)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:233 +0x7c
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0x1b1fd40)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:226 +0x39
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff({0x0, 0x0, 0x0, 0x1, 0x0}, 0x4)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:421 +0x5f
sigs.k8s.io/azurefile-csi-driver/pkg/azurefile.(*Driver).CreateVolume(0xc000182780, {0x1eb6db8, 0xc0000ea630}, 0xc00009b030)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/pkg/azurefile/controllerserver.go:369 +0x3fda
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler.func1({0x1eb6db8, 0xc0000ea630}, {0x1b4d760, 0xc00009b030})
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5676 +0x78
sigs.k8s.io/azurefile-csi-driver/pkg/csi-common.logGRPC({0x1eb6db8, 0xc0000ea630}, {0x1b4d760, 0xc00009b030}, 0xc0003418a0, 0xc0003a68a0)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/pkg/csi-common/utils.go:79 +0x3ab
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler({0x1bf3400, 0xc000182780}, {0x1eb6db8, 0xc0000ea630}, 0xc0002e8480, 0x1d0eff8)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5678 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a1c00, {0x1ee5428, 0xc00051e780}, 0xc00024fe60, 0xc00049b680, 0x2d60900, 0x0)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/google.golang.org/grpc/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002a1c00, {0x1ee5428, 0xc00051e780}, 0xc00024fe60, 0x0)
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/google.golang.org/grpc/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/google.golang.org/grpc/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/root/go/src/sigs.k8s.io/azurefile-csi-driver/vendor/google.golang.org/grpc/server.go:919 +0x294
```
Below is the storage class config
```
provisioner: file.csi.azure.com
    parameters:
      skuname: Premium_LRS
      protocol: nfs
      networkendpointtype: privateendpoint
    volumeBindingMode: WaitForFirstConsumer
```
Can you please take a look and suggest something ?

**Comment by andyzhangx** [comment]
could you get the driver controller logs? follow by: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/docs/csi-debug.md#case1-volume-createdelete-issue

panic happens here which means `az.getSubnet(vnetName, subnetName)` actually failed, `subnet.SubnetPropertiesFormat` is nil
https://github.com/kubernetes-sigs/cloud-provider-azure/blob/df2e05ad39d0b1747ff04cdf20bae5dc65817902/pkg/provider/azure_storageaccount.go#L337

**Comment by gauravAggrahari** [comment]
Yes, it used to work with 1.9.0 even if the `subnetName` was not specified. 
we created `azure-cloud-provider` secret using these params.
```
"tenantId" \
  "subscriptionId" \
  "aadClientId" \
  "aadClientSecret" \
  "resourceGroup" \
  "location" \
  "vmType" \
  "securityGroupName" \
  "vnetName"
```

**Comment by gauravAggrahari** [comment]
Hi @andyzhangx ,
I think it should fail for `1.9.0` as well. Seems like we had a pre created storage account while testing the `1.9.0` that is why it worked. 
What could be the proper solution for this ?
Can we specify any of the subnets ?

**Comment by andyzhangx** [comment]
> Hi @andyzhangx , I think it should fail for `1.9.0` as well. Seems like we had a pre created storage account while testing the `1.9.0` that is why it worked. What could be the proper solution for this ? Can we specify any of the subnets ?

@gauravAggrahari I think you could specify one subnet, and schedule the pod with nfs mount to the nodes in that subnet first. And then update private endpoint with the other subnets, I am not sure whether that's possible since from `PrivateEndpointProperties struct`, it only accepts one `Subnet`, not sure whether supports multiple subnets for private endpoint.

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/b94706783514d91947f2825007d7298235a562e0/vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_storageaccount.go#L351-L355


```
// PrivateEndpointProperties properties of the private endpoint.
type PrivateEndpointProperties struct {
	// Subnet - The ID of the subnet from which the private IP will be allocated.
	Subnet *Subnet `json:"subnet,omitempty"`
	// NetworkInterfaces - READ-ONLY; An array of references to the network interfaces created for this private endpoint.
	NetworkInterfaces *[]Interface `json:"networkInterfaces,omitempty"`
	// ProvisioningState - READ-ONLY; The provisioning state of the private endpoint resource. Possible values include: 'Succeeded', 'Updating', 'Deleting', 'Failed'
	ProvisioningState ProvisioningState `json:"provisioningState,omitempty"`
	// PrivateLinkServiceConnections - A grouping of information about the connection to the remote resource.
	PrivateLinkServiceConnections *[]PrivateLinkServiceConnection `json:"privateLinkServiceConnections,omitempty"`
	// ManualPrivateLinkServiceConnections - A grouping of information about the connection to the remote resource. Used when the network admin does not have access to approve connections to the remote resource.
	ManualPrivateLinkServiceConnections *[]PrivateLinkServiceConnection `json:"manualPrivateLinkServiceConnections,omitempty"`
	// CustomDNSConfigs - An array of custom dns configurations.
	CustomDNSConfigs *[]CustomDNSConfigPropertiesFormat `json:"customDnsConfigs,omitempty"`
}
```
