### ISSUE TITLE
fix Windows Unit Test failures

### ISSUE THREAD

**Issue by andyzhangx** [kubernetes-sigs/azurefile-csi-driver#365]
**What happened**:
After enabled running unit tests on Windows: https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/10d234801dc4251bf1923677a0e477c7451e53f2/.github/workflows/windows.yml#L1-L28

failed with following:
https://github.com/kubernetes-sigs/azurefile-csi-driver/runs/965044029?check_suite_focus=true
```
2020-08-10T02:57:15.7715380Z === RUN   TestGetCloudProvider
2020-08-10T02:57:15.7715898Z W0810 02:57:15.581388    5460 azure.go:42] get kubeconfig() failed with error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
2020-08-10T02:57:15.7716705Z E0810 02:57:15.685394    5460 azure.go:71] Failed to load config from file: C:\k\azure.json
2020-08-10T02:57:15.7723044Z ##[error]    azure_test.go:137: desc: [failure] out of cluster, no kubeconfig, no credential file,
2020-08-10T02:57:15.7729216Z          input: "", GetCloudProvider err: Failed to load config from file: C:\k\azure.json, cloud not get azure cloud provider, expectedErr: Failed to load config from file: /etc/kubernetes/azure.json, cloud not get azure cloud provider
2020-08-10T02:57:15.7729846Z W0810 02:57:15.685394    5460 azure.go:42] get kubeconfig(/tmp/non-exist.json) failed with error: CreateFile /tmp/non-exist.json: The system cannot find the path specified.
2020-08-10T02:57:15.7733097Z E0810 02:57:15.685394    5460 azure.go:71] Failed to load config from file: C:\k\azure.json
2020-08-10T02:57:15.7734772Z ##[error]    azure_test.go:137: desc: [failure] out of cluster & in cluster, specify a non-exist kubeconfig, no credential file,
2020-08-10T02:57:15.7735871Z          input: "/tmp/non-exist.json", GetCloudProvider err: Failed to load config from file: C:\k\azure.json, cloud not get azure cloud provider, expectedErr: Failed to load config from file: /etc/kubernetes/azure.json, cloud not get azure cloud provider
2020-08-10T02:57:15.7736479Z W0810 02:57:15.686394    5460 azure.go:42] get kubeconfig(empty-kube-config) failed with error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
2020-08-10T02:57:15.7764087Z W0810 02:57:15.733398    5460 azure_config.go:52] Failed to get cloud-config from secret: failed to get secret azure-cloud-provider: Get "https://localhost:8080/api/v1/namespaces/kube-system/secrets/azure-cloud-provider": getting credentials: exec: exec: "foo-command": executable file not found in %PATH%, skip initializing from secret
2020-08-10T02:57:15.7765889Z E0810 02:57:15.734398    5460 azure.go:71] Failed to load config from file: C:\k\azure.json
2020-08-10T02:57:15.7776516Z ##[error]    azure_test.go:137: desc: [failure] out of cluster & in cluster, specify a fake kubeconfig, no credential file,
2020-08-10T02:57:15.7779184Z          input: "fake-kube-config", GetCloudProvider err: Failed to load config from file: C:\k\azure.json, cloud not get azure cloud provider, expectedErr: Failed to load config from file: /etc/kubernetes/azure.json, cloud not get azure cloud provider
2020-08-10T02:57:15.7779860Z W0810 02:57:15.734398    5460 azure.go:42] get kubeconfig() failed with error: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
2020-08-10T02:57:15.7780523Z --- FAIL: TestGetCloudProvider (0.15s)
2020-08-10T02:57:15.7781007Z === RUN   TestNewFakeDriver
2020-08-10T02:57:15.7781456Z --- PASS: TestNewFakeDriver (0.00s)
2020-08-10T02:57:15.7782803Z === RUN   TestAppendDefaultMountOptions
2020-08-10T02:57:15.7784153Z --- PASS: TestAppendDefaultMountOptions (0.00s)
2020-08-10T02:57:15.7784708Z === RUN   TestGetFileShareInfo
2020-08-10T02:57:15.7835583Z --- PASS: TestGetFileShareInfo (0.00s)
2020-08-10T02:57:15.7850372Z === RUN   TestGetStorageAccount
2020-08-10T02:57:15.7852259Z --- PASS: TestGetStorageAccount (0.00s)
2020-08-10T02:57:15.7852806Z === RUN   TestGetValidFileShareName
2020-08-10T02:57:15.7853237Z W0810 02:57:15.740398    5460 azurefile.go:311] the requested volume name ("aq") is invalid, so it is regenerated as ("pvc-file-dynamic-32614a3a-dab5-11ea-8bd7-000d3a04d5c4")
2020-08-10T02:57:15.7853622Z --- PASS: TestGetValidFileShareName (0.00s)
2020-08-10T02:57:15.7854078Z === RUN   TestCheckShareNameBeginAndEnd
2020-08-10T02:57:15.7854527Z --- PASS: TestCheckShareNameBeginAndEnd (0.00s)
2020-08-10T02:57:15.7854862Z === RUN   TestGetSnapshot
2020-08-10T02:57:15.7855195Z --- PASS: TestGetSnapshot (0.00s)
2020-08-10T02:57:15.7855549Z === RUN   TestIsCorruptedDir
2020-08-10T02:57:15.7855990Z IsCorruptedDir(/tmp/NotExist) returned with error: <nil>IsCorruptedDir(C:\Users\RUNNER~1\AppData\Local\Temp\csi-mount-test655270115) returned with error: <nil>--- PASS: TestIsCorruptedDir (0.00s)
2020-08-10T02:57:15.7856358Z === RUN   TestNewDriver
2020-08-10T02:57:15.7856685Z --- PASS: TestNewDriver (0.00s)
2020-08-10T02:57:15.7857014Z === RUN   TestGetFileURL
2020-08-10T02:57:15.7857266Z --- PASS: TestGetFileURL (0.00s)
2020-08-10T02:57:15.7857815Z === RUN   TestGetAccountInfo
2020-08-10T02:57:15.7858129Z --- PASS: TestGetAccountInfo (0.00s)
2020-08-10T02:57:15.7858460Z === RUN   TestCreateDisk
2020-08-10T02:57:15.7858775Z --- FAIL: TestCreateDisk (0.00s)
2020-08-10T02:57:15.7859083Z panic: open /dev/urandom: The system cannot find the path specified. [recovered]
2020-08-10T02:57:15.7859411Z 	panic: open /dev/urandom: The system cannot find the path specified.
2020-08-10T02:57:15.7859642Z 
2020-08-10T02:57:15.7859912Z goroutine 36 [running]:
2020-08-10T02:57:15.7860247Z testing.tRunner.func1.1(0x22eac20, 0xc00042e1b0)
2020-08-10T02:57:15.7860541Z 	C:/hostedtoolcache/windows/go/1.14.6/x64/src/testing/testing.go:988 +0x459
2020-08-10T02:57:15.7860884Z testing.tRunner.func1(0xc00019a7e0)
2020-08-10T02:57:15.7861204Z 	C:/hostedtoolcache/windows/go/1.14.6/x64/src/testing/testing.go:991 +0x607
2020-08-10T02:57:15.7861698Z panic(0x22eac20, 0xc00042e1b0)
2020-08-10T02:57:15.7862005Z 	C:/hostedtoolcache/windows/go/1.14.6/x64/src/runtime/panic.go:975 +0x3f1
2020-08-10T02:57:15.7862359Z github.com/rubiojr/go-vhd/vhd.check(...)
2020-08-10T02:57:15.7862695Z 	C:/Users/runneradmin/go/pkg/mod/github.com/rubiojr/go-vhd@v0.0.0-20200706105327-02e210299021/vhd/util.go:31
2020-08-10T02:57:15.7863047Z github.com/rubiojr/go-vhd/vhd.uuidgenBytes(0xc000015780, 0x8, 0xc000008840)
2020-08-10T02:57:15.7863394Z 	C:/Users/runneradmin/go/pkg/mod/github.com/rubiojr/go-vhd@v0.0.0-20200706105327-02e210299021/vhd/util.go:23 +0x135
2020-08-10T02:57:15.7863855Z github.com/rubiojr/go-vhd/vhd.CreateFixedHeader(0x14, 0xc000015780, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-08-10T02:57:15.7864456Z 	C:/Users/runneradmin/go/pkg/mod/github.com/rubiojr/go-vhd@v0.0.0-20200706105327-02e210299021/vhd/vhd.go:188 +0x8b6
2020-08-10T02:57:15.7865020Z sigs.k8s.io/azurefile-csi-driver/pkg/azurefile.createDisk(0x28149e0, 0xc00003a110, 0x24ee024, 0x17, 0x24d42ce, 0x3, 0x24d7155, 0x6, 0x25251ea, 0x35, ...)
2020-08-10T02:57:15.7865342Z 	D:/a/azurefile-csi-driver/azurefile-csi-driver/pkg/azurefile/azurefile.go:368 +0x93
2020-08-10T02:57:15.7865716Z sigs.k8s.io/azurefile-csi-driver/pkg/azurefile.TestCreateDisk(0xc00019a7e0)
2020-08-10T02:57:15.7866010Z 	D:/a/azurefile-csi-driver/azurefile-csi-driver/pkg/azurefile/azurefile_test.go:635 +0x56b
2020-08-10T02:57:15.7866358Z testing.tRunner(0xc00019a7e0, 0x2597580)
2020-08-10T02:57:15.7866634Z 	C:/hostedtoolcache/windows/go/1.14.6/x64/src/testing/testing.go:1039 +0x1f3
2020-08-10T02:57:15.7866941Z created by testing.(*T).Run
2020-08-10T02:57:15.7867222Z 	C:/hostedtoolcache/windows/go/1.14.6/x64/src/testing/testing.go:1090 +0x708
2020-08-10T02:57:15.7867586Z FAIL	sigs.k8s.io/azurefile-csi-driver/pkg/azurefile	0.265s
2020-08-10T02:57:16.4148104Z ?   	sigs.k8s.io/azurefile-csi-driver/pkg/azurefileplugin	[no test files]
2020-08-10T02:57:17.8735769Z # sigs.k8s.io/azurefile-csi-driver/pkg/mounter
2020-08-10T02:57:17.8745305Z ##[error]pkg\mounter\safe_mounter_windows.go:64:3: Infof format %s reads arg #1, but call has 0 args
2020-08-10T02:57:19.5557443Z === RUN   TestValidateVolumeCapabilities
2020-08-10T02:57:19.5581411Z I0810 02:57:17.489486    3484 driver.go:112] Enabling volume access mode: SINGLE_NODE_WRITER
2020-08-10T02:57:19.5601065Z I0810 02:57:17.522487    3484 driver.go:112] Enabling volume access mode: SINGLE_NODE_READER_ONLY
2020-08-10T02:57:19.5646336Z I0810 02:57:17.522487    3484 driver.go:112] Enabling volume access mode: MULTI_NODE_READER_ONLY
2020-08-10T02:57:19.5647823Z --- PASS: TestValidateVolumeCapabilities (0.03s)
2020-08-10T02:57:19.5648454Z === RUN   TestControllerGetCapabilities
2020-08-10T02:57:19.5649020Z --- PASS: TestControllerGetCapabilities (0.00s)
2020-08-10T02:57:19.5649472Z === RUN   TestCreateVolume
2020-08-10T02:57:19.5649911Z --- PASS: TestCreateVolume (0.00s)
2020-08-10T02:57:19.5651540Z === RUN   TestDeleteVolume
2020-08-10T02:57:19.5651994Z --- PASS: TestDeleteVolume (0.00s)
2020-08-10T02:57:19.5652334Z === RUN   TestControllerPublishVolume
2020-08-10T02:57:19.5709342Z --- PASS: TestControllerPublishVolume (0.00s)
2020-08-10T02:57:19.5710017Z === RUN   TestControllerUnpublishVolume
2020-08-10T02:57:19.5710742Z --- PASS: TestControllerUnpublishVolume (0.00s)
2020-08-10T02:57:19.5714153Z === RUN   TestGetCapacity
2020-08-10T02:57:19.5735508Z --- PASS: TestGetCapacity (0.00s)
2020-08-10T02:57:19.5737097Z === RUN   TestListVolumes
2020-08-10T02:57:19.5737575Z --- PASS: TestListVolumes (0.00s)
2020-08-10T02:57:19.5737833Z === RUN   TestCreateSnapshot
2020-08-10T02:57:19.5738306Z --- PASS: TestCreateSnapshot (0.00s)
2020-08-10T02:57:19.5738611Z === RUN   TestDeleteSnapshot
2020-08-10T02:57:19.5738914Z --- PASS: TestDeleteSnapshot (0.00s)
2020-08-10T02:57:19.5739280Z === RUN   TestListSnapshots
2020-08-10T02:57:19.5739597Z --- PASS: TestListSnapshots (0.00s)
2020-08-10T02:57:19.5739896Z === RUN   TestNewFakeDriver
2020-08-10T02:57:19.5740803Z E0810 02:57:17.524487    3484 driver.go:40] Driver name missing
2020-08-10T02:57:19.5741249Z E0810 02:57:17.524487    3484 driver.go:45] NodeID missing
2020-08-10T02:57:19.5741591Z E0810 02:57:17.524487    3484 driver.go:50] Version argument missing, now skip it
2020-08-10T02:57:19.5741919Z --- PASS: TestNewFakeDriver (0.00s)
2020-08-10T02:57:19.5742240Z === RUN   TestGetVolumeCapabilityAccessModes
2020-08-10T02:57:19.5742580Z I0810 02:57:17.524487    3484 driver.go:112] Enabling volume access mode: SINGLE_NODE_WRITER
2020-08-10T02:57:19.5742927Z --- PASS: TestGetVolumeCapabilityAccessModes (0.00s)
2020-08-10T02:57:19.5743260Z === RUN   TestValidateControllerServiceRequest
2020-08-10T02:57:19.5743535Z I0810 02:57:17.524487    3484 driver.go:93] Enabling controller service capability: CREATE_DELETE_VOLUME
2020-08-10T02:57:19.5743880Z I0810 02:57:17.524487    3484 driver.go:93] Enabling controller service capability: PUBLISH_UNPUBLISH_VOLUME
2020-08-10T02:57:19.5744217Z I0810 02:57:17.524487    3484 driver.go:93] Enabling controller service capability: GET_CAPACITY
2020-08-10T02:57:19.5744551Z I0810 02:57:17.524487    3484 driver.go:93] Enabling controller service capability: LIST_VOLUMES
2020-08-10T02:57:19.5744894Z --- PASS: TestValidateControllerServiceRequest (0.00s)
2020-08-10T02:57:19.5745218Z === RUN   TestValidateNodeServiceRequest
2020-08-10T02:57:19.5745584Z --- PASS: TestValidateNodeServiceRequest (0.00s)
2020-08-10T02:57:19.5745887Z === RUN   TestGetPluginInfo
2020-08-10T02:57:19.5746197Z E0810 02:57:17.525488    3484 driver.go:50] Version argument missing, now skip it
2020-08-10T02:57:19.5746521Z --- PASS: TestGetPluginInfo (0.00s)
2020-08-10T02:57:19.5746805Z === RUN   TestProbe
2020-08-10T02:57:19.5747094Z --- PASS: TestProbe (0.00s)
2020-08-10T02:57:19.5747399Z === RUN   TestGetPluginCapabilities
2020-08-10T02:57:19.5747909Z --- PASS: TestGetPluginCapabilities (0.00s)
2020-08-10T02:57:19.5748221Z === RUN   TestNodeGetInfo
2020-08-10T02:57:19.5748519Z --- PASS: TestNodeGetInfo (0.00s)
2020-08-10T02:57:19.5748824Z === RUN   TestNodeGetCapabilities
2020-08-10T02:57:19.5749577Z --- PASS: TestNodeGetCapabilities (0.00s)
2020-08-10T02:57:19.5749858Z === RUN   TestNewNonBlockingGRPCServer
2020-08-10T02:57:19.5750795Z --- PASS: TestNewNonBlockingGRPCServer (0.00s)
2020-08-10T02:57:19.5751121Z === RUN   TestStart
2020-08-10T02:57:19.5751416Z --- PASS: TestStart (0.00s)
2020-08-10T02:57:19.5751723Z === RUN   TestServe
2020-08-10T02:57:19.5752055Z I0810 02:57:17.527487    3484 server.go:118] Listening for connections on address: &net.TCPAddr{IP:net.IP{0x7f, 0x0, 0x0, 0x1}, Port:49941, Zone:""}
2020-08-10T02:57:19.5752415Z I0810 02:57:17.527487    3484 server.go:118] Listening for connections on address: &net.TCPAddr{IP:net.IP{0x7f, 0x0, 0x0, 0x1}, Port:49942, Zone:""}
2020-08-10T02:57:19.5752738Z --- PASS: TestServe (1.00s)
2020-08-10T02:57:19.5753029Z === RUN   TestWait
2020-08-10T02:57:19.5753319Z --- PASS: TestWait (0.00s)
2020-08-10T02:57:19.5753598Z === RUN   TestStop
2020-08-10T02:57:19.5753887Z --- PASS: TestStop (0.00s)
2020-08-10T02:57:19.5754187Z === RUN   TestForceStop
2020-08-10T02:57:19.5754610Z --- PASS: TestForceStop (0.00s)
2020-08-10T02:57:19.5754858Z === RUN   TestParseEndpoint
2020-08-10T02:57:19.5755159Z --- PASS: TestParseEndpoint (0.00s)
2020-08-10T02:57:19.5755445Z === RUN   TestLogGRPC
2020-08-10T02:57:19.5755749Z === RUN   TestLogGRPC/with_secrets
2020-08-10T02:57:19.5756055Z === RUN   TestLogGRPC/without_secrets
2020-08-10T02:57:19.5756373Z --- PASS: TestLogGRPC (0.00s)
2020-08-10T02:57:19.5756643Z     --- PASS: TestLogGRPC/with_secrets (0.00s)
2020-08-10T02:57:19.5756963Z     --- PASS: TestLogGRPC/without_secrets (0.00s)
2020-08-10T02:57:19.5757281Z === RUN   TestNewDefaultNodeServer
2020-08-10T02:57:19.5757583Z --- PASS: TestNewDefaultNodeServer (0.00s)
2020-08-10T02:57:19.5757900Z === RUN   TestNewDefaultIdentityServer
2020-08-10T02:57:19.5758208Z --- PASS: TestNewDefaultIdentityServer (0.00s)
2020-08-10T02:57:19.5758513Z === RUN   TestNewDefaultControllerServer
2020-08-10T02:57:19.5758779Z --- PASS: TestNewDefaultControllerServer (0.00s)
2020-08-10T02:57:19.5759102Z === RUN   TestNewVolumeCapabilityAccessMode
2020-08-10T02:57:19.5759411Z --- PASS: TestNewVolumeCapabilityAccessMode (0.00s)
2020-08-10T02:57:19.5909296Z === RUN   TestNewControllerServiceCapability
2020-08-10T02:57:19.5909599Z --- PASS: TestNewControllerServiceCapability (0.00s)
2020-08-10T02:57:19.5909795Z === RUN   TestNewNodeServiceCapability
2020-08-10T02:57:19.5910248Z --- PASS: TestNewNodeServiceCapability (0.00s)
2020-08-10T02:57:19.5910619Z PASS
2020-08-10T02:57:19.5910941Z ok  	sigs.k8s.io/azurefile-csi-driver/pkg/csi-common	2.268s
2020-08-10T02:57:19.5911344Z FAIL	sigs.k8s.io/azurefile-csi-driver/pkg/mounter [build failed]
2020-08-10T02:57:19.5911610Z === RUN   TestRoundUpBytes
2020-08-10T02:57:19.5911882Z --- PASS: TestRoundUpBytes (0.00s)
2020-08-10T02:57:19.5912128Z === RUN   TestRoundUpGiB
2020-08-10T02:57:19.5912391Z --- PASS: TestRoundUpGiB (0.00s)
2020-08-10T02:57:19.5912639Z === RUN   TestBytesToGiB
2020-08-10T02:57:19.5912949Z --- PASS: TestBytesToGiB (0.00s)
2020-08-10T02:57:19.5913206Z === RUN   TestGiBToBytes
2020-08-10T02:57:19.5913460Z --- PASS: TestGiBToBytes (0.00s)
2020-08-10T02:57:19.5913679Z PASS
2020-08-10T02:57:19.5913979Z ok  	sigs.k8s.io/azurefile-csi-driver/pkg/util	1.033s
2020-08-10T02:57:21.0370277Z === RUN   TestCreateAzureCredentialFileOnAzureChinaCloud
2020-08-10T02:57:21.0371014Z === RUN   TestCreateAzureCredentialFileOnAzureChinaCloud/WithAzureCredentials
2020-08-10T02:57:21.0371488Z 2020/08/10 02:57:20 Running in Prow, converting AZURE_CREDENTIALS to AZURE_CREDENTIAL_FILE
2020-08-10T02:57:21.0371857Z 2020/08/10 02:57:21 Reading credentials file C:\Users\RUNNER~1\AppData\Local\Temp\azure.toml054811655
2020-08-10T02:57:21.0373451Z     credentials_test.go:99: 
2020-08-10T02:57:21.0374100Z         	Error Trace:	credentials_test.go:99
2020-08-10T02:57:21.0374453Z         	            				credentials_test.go:49
2020-08-10T02:57:21.0374776Z         	Error:      	Received unexpected error:
2020-08-10T02:57:21.0375211Z         	            	error creating /tmp/azure.json open /tmp/azure.json: The system cannot find the path specified.
2020-08-10T02:57:21.0375588Z         	Test:       	TestCreateAzureCredentialFileOnAzureChinaCloud/WithAzureCredentials
2020-08-10T02:57:21.0376261Z     credentials_test.go:90: 
2020-08-10T02:57:21.0378560Z         	Error Trace:	credentials_test.go:90
2020-08-10T02:57:21.0383750Z         	            				panic.go:975
2020-08-10T02:57:21.0384124Z         	            				panic.go:212
2020-08-10T02:57:21.0384497Z         	            				signal_windows.go:246
2020-08-10T02:57:21.0384809Z         	            				credentials_test.go:112
2020-08-10T02:57:21.0385120Z         	            				credentials_test.go:49
2020-08-10T02:57:21.0385432Z         	Error:      	Received unexpected error:
2020-08-10T02:57:21.0385886Z         	            	remove C:\Users\RUNNER~1\AppData\Local\Temp\azure.toml054811655: The process cannot access the file because it is being used by another process.
2020-08-10T02:57:21.0386605Z         	Test:       	TestCreateAzureCredentialFileOnAzureChinaCloud/WithAzureCredentials
2020-08-10T02:57:21.0386980Z --- FAIL: TestCreateAzureCredentialFileOnAzureChinaCloud (0.04s)
2020-08-10T02:57:21.0387315Z     --- FAIL: TestCreateAzureCredentialFileOnAzureChinaCloud/WithAzureCredentials (0.04s)
2020-08-10T02:57:21.0387816Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2020-08-10T02:57:21.0388123Z 	panic: runtime error: invalid memory address or nil pointer dereference
2020-08-10T02:57:21.0388438Z [signal 0xc0000005 code=0x0 addr=0x0 pc=0x9a7c1e]
2020-08-10T02:57:21.0388638Z 
2020-08-10T02:57:21.0388901Z goroutine 20 [running]:
2020-08-10T02:57:21.0389193Z testing.tRunner.func1.1(0xa024e0, 0xe41e10)
2020-08-10T02:57:21.0389458Z 	C:/hostedtoolcache/windows/go/1.14.6/x64/src/testing/testing.go:988 +0x459
2020-08-10T02:57:21.0389900Z testing.tRunner.func1(0xc0000e8a20)
2020-08-10T02:57:21.0390152Z 	C:/hostedtoolcache/windows/go/1.14.6/x64/src/testing/testing.go:991 +0x607
2020-08-10T02:57:21.0390626Z panic(0xa024e0, 0xe41e10)
2020-08-10T02:57:21.0390926Z 	C:/hostedtoolcache/windows/go/1.14.6/x64/src/runtime/panic.go:975 +0x3f1
2020-08-10T02:57:21.0391732Z sigs.k8s.io/azurefile-csi-driver/test/utils/credentials.withAzureCredentials(0xc0000e8a20, 0x1)
2020-08-10T02:57:21.0392098Z 	D:/a/azurefile-csi-driver/azurefile-csi-driver/test/utils/credentials/credentials_test.go:112 +0x30e
2020-08-10T02:57:21.0392524Z sigs.k8s.io/azurefile-csi-driver/test/utils/credentials.TestCreateAzureCredentialFileOnAzureChinaCloud.func1(0xc0000e8a20)
2020-08-10T02:57:21.0392810Z 	D:/a/azurefile-csi-driver/azurefile-csi-driver/test/utils/credentials/credentials_test.go:49 +0x129
2020-08-10T02:57:21.0393116Z testing.tRunner(0xc0000e8a20, 0xa8b750)
2020-08-10T02:57:21.0393351Z 	C:/hostedtoolcache/windows/go/1.14.6/x64/src/testing/testing.go:1039 +0x1f3
2020-08-10T02:57:21.0393606Z created by testing.(*T).Run
2020-08-10T02:57:21.0394017Z 	C:/hostedtoolcache/windows/go/1.14.6/x64/src/testing/testing.go:1090 +0x708
2020-08-10T02:57:21.0394348Z FAIL	sigs.k8s.io/azurefile-csi-driver/test/utils/credentials	0.183s
2020-08-10T02:57:21.0394769Z FAIL
2020-08-10T02:57:21.9027433Z ##[error]Process completed with exit code 1.
2020-08-10T02:57:21.9188105Z Post job cleanup.
2020-08-10T02:57:23.8140910Z [command]"C:\Program Files\Git\bin\git.exe" version
2020-08-10T02:57:23.8330268Z git version 2.28.0.windows.1
2020-08-10T02:57:23.8400218Z [command]"C:\Program Files\Git\bin\git.exe" config --local --name-only --get-regexp core\.sshCommand
2020-08-10T02:57:23.8627865Z [command]"C:\Program Files\Git\bin\git.exe" submodule foreach --recursive "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2020-08-10T02:57:24.3475308Z [command]"C:\Program Files\Git\bin\git.exe" config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2020-08-10T02:57:24.3652943Z http.https://github.com/.extraheader
2020-08-10T02:57:24.3699687Z [command]"C:\Program Files\Git\bin\git.exe" config --local --unset-all http.https://github.com/.extraheader
2020-08-10T02:57:24.3927921Z [command]"C:\Program Files\Git\bin\git.exe" submodule foreach --recursive "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2020-08-10T02:57:24.8756899Z Cleaning up orphan processes
```

**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- CSI Driver version:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
already fixed by https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/.github/workflows/windows.yml
